server:
  port: 8081

eureka:
  instance:
    hostname: ${HOSTNAME:vsts}
  client:
    serviceUrl:
      defaultZone: http://registry:8761/eureka/

rp:
  mongo:
    uri: mongodb://mongodb:27017
    #host: ${reportportal.mongo.host:mongodb}
    #port: 27017
    dbName: reportportal
    #user:
    #password:

spring:
  redis:
    host: redis
    port: 6379
  cloud:
    consul:
      host: registry
      discovery:
        hostname: ${HOSTNAME:vsts}
        prefer-ip-address: false