# Server Configuration
server:
  port: 8081

#endpoints:
#  health:
#    sensitive: false
#management:
#  security:
#    enabled: false

# MongoDB configuration
rp:
  mongo:
    uri: mongodb://mongodb:27017
#    host: ${reportportal.mongo.host:mongodb}
#    port: 27017
    dbName: reportportal
    #        user: user
    #        password: 1q2w3e
    connectionsPerHost: 1000
    threadsAllowedToBlockForConnectionMultiplier: 1000
    connectTimeout: 20000
    socketTimeout: 60000
    maxWaitTime: 120000
    autoConnectRetry: true
    socketKeepAlive: true
    slaveOk: true
    writeTimeout: 0
    writeNumber: 1
    writeFsync: false
  cache:
    project:
      size: 1000
      expiration: 1
      info: 10
    ticket:
      size: 10000
      expiration: 5
    user:
      size: 1000
      expiration: 60

# Eureka Configuration
eureka:
  instance:
    status-page-url-path: ${server.contextPath:}/info
    health-check-url-path: ${server.contextPath:}/health
    hostname: ${reportportal.eureka.instance.hostname:localhost}
    metadata-map:
      extension: vsts

  client:
    serviceUrl:
      defaultZone: http://${reportportal.eureka.hostname:localhost}:8761/eureka/
    enabled: false
    register-with-eureka: false

spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        tags:
        - urlprefix-${server.context-path:}/vsts opts strip=/vsts
        - traefik.frontend.rule=PathPrefixStrip:${server.context-path:}/vsts
        - statusPageUrlPath=${server.contextPath:}/info
        - healthCheckUrlPath=${server.contextPath:}/health
        - extension=vsts
        healthCheckPath: ${server.contextPath:}/health
        register: true
        health-check-critical-timeout: 30s
      enabled: true

## Consul as service registry
---
spring:
  profiles: consul
  cloud:
    consul:
      enabled: true
      discovery:
        register: true
eureka:
  client:
    register-with-eureka: false
    enabled: false

## Eureka as service registry
---
spring:
  profiles: eureka
  cloud:
    consul:
      enabled: false
      discovery:
        register: false
eureka:
  client:
    register-with-eureka: true
    enabled: true
---
