FROM frolvlad/alpine-oraclejdk8:slim

MAINTAINER Ernesto Barbosa <ernestosbarbosa@outlook.com>

VOLUME /tmp

ADD https://dl.bintray.com/epam/reportportal/com/epam/reportportal/${project.name}/${version}/${project.name}-${version}.jar /app.jar

RUN sh -c 'touch /app.jar'

EXPOSE 8081

ENTRYPOINT ["java","-Xmx256m","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
